var maptileW = [
    // 1       2       3       4       5       6       7       8       9       10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 1
    ['tile','tileP','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 2
    ['tileW','tile','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 3
    ['tileW','tile','tileW','tile','tile','tile','tile','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 4
    ['tileW','tile','tileW','tile','tile','tileE','tile','tileE','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 5
    ['tileW','tile','tileW','tile','tile','tile','tile','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 6
    ['tileW','tile','tileW','tile','tile','tile','tile','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 7
    ['tileW','tile','tileW','tile','tileSW','tile','tileHP','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 8
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 9
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 10
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 11
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 12
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 13
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 14
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 15
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 16
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 17
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 18
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 19
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 20
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 21
    ['tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 22
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 23
    ['tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tile','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW','tileW'], // 24
]